CREATE TABLE USUARIOS(
IDUSER varchar(100),
PASSWORD varchar(50) NOT NULL,
NOMBRE varchar(100),
APELLIDOS varchar(100),
EMAIL varchar(100),
ULTIMA_CONEXION datetime,
CONSTRAINT pk_usuarios PRIMARY KEY (IDUSER));

CREATE TABLE CONVERSACIONES(
IDCONVERSACION int(100),
CONSTRAINT pk_conversacion PRIMARY KEY(IDCONVERSACION));

CREATE TABLE MENSAJES(
IDMENSAJE int AUTO_INCREMENT,
EMISOR varchar(100) NOT NULL,
RECEPTOR varchar(100) NOT NULL,
TEXTO varchar(65000) NOT NULL,
CONVERSACION int(100),
FECHA datetime NOT NULL default now(),
CONSTRAINT pk_mensaje PRIMARY KEY(IDMENSAJE),
CONSTRAINT fk_mensaje_usuarios_e FOREIGN KEY (EMISOR) REFERENCES USUARIOS(IDUSER),
CONSTRAINT fk_mensaje_usuarios_r FOREIGN KEY (RECEPTOR) REFERENCES USUARIOS(IDUSER),
CONSTRAINT fk_mensaje_conversacion FOREIGN KEY (CONVERSACION) REFERENCES CONVERSACIONES(IDCONVERSACION));

CREATE TABLE PARTICIPANTES(
USER varchar(100),
IDCONVERSACION int(100),
CONSTRAINT pk_participantes PRIMARY KEY(USER,IDCONVERSACION),
CONSTRAINT fk_participantes_usuarios_e FOREIGN KEY (USER) REFERENCES USUARIOS(IDUSER),
CONSTRAINT fk_participantes_conversacion FOREIGN KEY (IDCONVERSACION) REFERENCES CONVERSACIONES(IDCONVERSACION));

CREATE TABLE CONEXIONES(
IDCONEXION integer AUTO_INCREMENT,
IP varchar(16),
USUARIO varchar(100),
ULTIMA_ACTUALIZACION datetime,
CONSTRAINT pk_conexiones PRIMARY KEY(IDCONEXION),
CONSTRAINT fk_conexiones_usuarios FOREIGN KEY (USUARIO) REFERENCES USUARIOS(IDUSER));
